### ISSUE TITLE
Areaportals with splitting polygon with more than 4 vertexes are decompiled incorrectly

### ISSUE THREAD

**Issue by stepa2** [ata4/bspsrc#116]
If areaportal's splitting polygon has more than 4 vertexes, than only (probably first) 4 vertexes are taken and decompiled.
![изображение](https://user-images.githubusercontent.com/24942438/95571007-74402180-0a30-11eb-9f0a-e7a4262de4ce.png)

**Comment by rihi** [comment]
Which version of the decompiler did you use to decompile this map?
This results looks like something version 1.3.24 would produce, which is no longer the newest version.
You can find all releases [here](https://github.com/ata4/bspsrc/releases).

**Comment by stepa2** [comment]
Version 1.4.0 was used

**Comment by rihi** [comment]
Hm, that's rather weird for that specific version.
Can you provide the map in question, so I could try figuring out what's happening?

**Comment by stepa2** [comment]
https://drive.google.com/file/d/1_iK5k-ZK8oANFBPMgEwaSiGQFu_6S_RS/view?usp=sharing

**Comment by rihi** [comment]
I tried decompiling your map with the newest version of bspsrc but couldn't reproduce the result you got. Here is what the areaportal in your screenshot looks for me.

![grafik](https://user-images.githubusercontent.com/19492038/97118506-90b7ab80-170a-11eb-8095-b9c2da58f109.png)
(I was missing the textures embedded into the map, which is why everything is in gray shades)

**Comment by stepa2** [comment]
For some reason I can not reproduce it too.
