### ISSUE TITLE
Cyber Diver Map Support

### ISSUE THREAD

**Issue by TheKins** [ata4/bspsrc#24]
**Expected Behavior**
Cyber Diver maps correctly load and decompile files that can load into Hammer.

**Observed Behavior**
bs_map_p001 causes an error when a decompile attempt is made. Other maps decompile, but seem to cause Hammer to close without an error message upon loading.

**Wait, WTF Is Cyber Diver**
An arcade game by Taito that uses a variant of the TF2 version of Source. You can find the BSP files [here](https://dl.dropboxusercontent.com/u/25843724/temp/cyberdiver_maps.7z).

I'm aware that this bug is very unlikely to be observed in normal use, what with only affecting a Japan-only arcade game, but hey, if you're bored one day, it might be something interesting to poke at. :)

**Comment by ata4** [comment]
One of the map has a clash with the game detection, since it has a similar file name pattern like Vindictus. If the game is manually set to "Half-Life 2: Episode Two", it seems to work fine. I may have to add the game to the list in order to fix that.

Regarding Hammer crashing, the program is super helpful with its verbose error output, as usual. /s

Turns out Hammer crashes when it loads env_sprites with "Sprite Name" prefixed with "models" while "Scale" is also set. No idea why. You can easily reproduce it by creating a new map with an env_sprite, setting its scale to 1 and then setting the sprite name to "models", Hammer will crash instantly when hitting enter. I guess I'll have to add a workaround for this special case.

Also, sorry for the very late reply. I switch between my projects from time to time and can't really focus on more than one.
