### ISSUE TITLE
Decompiling error, caused by java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by LethalDumpster** [ata4/bspsrc#53]
Garry'sMod workshop map. I get this, and the output vmf contains no data. Im actually a little surprised I couldnt find any answers to this. Anybody know whats up?

[error] BspSource: Decompiling error, caused by java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at info.ata4.bspsrc.modules.VmfMeta.<init>(VmfMeta.java:59)
	at info.ata4.bspsrc.modules.BspDecompiler.<init>(BspDecompiler.java:57)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:127)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:67)
	at info.ata4.bspsrc.gui.BspSourceFrame$5.run(BspSourceFrame.java:364)

**Comment by gitRihi** [comment]
I had a quick look at the source code and it looks like the array containing all entities was empty for some reason. However, i don't really know why this could happen. If you can tell me what map you used I could have a look for myself and maybe figure what causes this.

**Comment by LethalDumpster** [comment]
I figured out the issue. This old map was used for a server I used to play, but the creators decided to separate a .lmp file from the .bsp to keep other servers at the time from using their map. I found the .lmp file for it, but I dont know how to put it back into the .bsp. You dont just so happen to know how to do that, do ya?

**Comment by gitRihi** [comment]
No, sorry. There may be tools out there to do that but i don’t know any. 
However, BSPSource should be able to do that as well. There’s an option in the „other“ tab which enables loading of external lumpfiles. The names of the files it is searching for are: „MAPNAME_l_LUMPINDEXNUMBER.lmp“.
Try placing the lump file in the same directory as the bsp file and see if it works that way.

**Comment by LethalDumpster** [comment]
Ive tried that before, but now that you mention it.. You just hinted me back into the right direction! Simply having the .lmp with the .bsp wont cut it. But doing that and having them both within the \maps folder does the trick! I originally had them in the extracted addon folder. But then I thought about how programs setup their directorys. Its not always going to search for files in the same place, but will likely search for files in designated locations. designated location = \maps

**Comment by KabusIblis** [comment]
For anyone that wishes to decompile a map that found themselves here because of this specific method of stopping maps from being decompiled in certain cases, the method that works is to include an empty .lmp file into the map and then use bspsrc to decompile the map.

This error is specifically because the bsp that is attempting to be decompiled is missing information that was patched into the map, either because of entities being removed or for it being used for its original purpose which is for changes to entities after compile.

For more specifics, [check this wiki link](https://developer.valvesoftware.com/wiki/Patching_levels_with_lump_files)

Note that this will **not reproduce 100% accurate maps**, it only allows for the geometry, props and for some entities if any are included in the .bsp to be decompiled into a .vmf

I'll attach an empty .lmp for the convenience for anyone thats attempting a map decompile that stumbles here, just rename it to your map and include  _l_0.lmp at the end, for example. `"mapname123_l_0.lmp"`

[blank_lmp.zip](https://github.com/ata4/bspsrc/files/3460149/blank_lmp.zip)

@gitRihi perhaphs this could be integrated into bspsrc of the user cannot locate a .lmp?
