### ISSUE TITLE
CS:GO and vindictus static prop scaling is not supported.

### ISSUE THREAD

**Issue by Stiffy360** [ata4/bspsrc#62]
CS:GO and Vindictus have support for the scaling of static props. However, this data is not decompiled and applied to the keyvalues of those props.

Not sure what k/v Vindictus uses, but CS:GO uses "uniformscale" "float" as it's k/v set.

I can provide a vindictus bsp if you need to test.

**Comment by gitRihi** [comment]
The uniformscale property support for csgo was actually merged into bspsrc a while ago. However, since then there was no new version released. So you would either have to compile bspsrc from this repository yourself or have to wait for a new version to be released (Which honestly doesn't seem to be likely as the original creator doesn't actively update this tool any more).

I could have a look for vindictus however. Maybe I can figure out how to support their scaling of static props and propose a pull request. Can you send me a vindictus bsp with scaled props? Because I don't have an SDK for it.

**Comment by Stiffy360** [comment]
@gitRihi Here's a bsp
https://www.mediafire.com/file/2djpwh7szgb6tin/new.zip/file

**Comment by gitRihi** [comment]
Sorry for my late reply.
I've looked into vindictus and I know where they save scaling of static props.
However, is there even an official SDK for this game? Or the compiling tool for maps (vbsp.exe)? Because without it, decompiling for the scaling attribute would be kinda pointless. Or even impossible, because I can't know what the attributes name for scaling is.

**Comment by Stiffy360** [comment]
@gitRihi 
There is neither an SDK or compile toolset for it. However, that information is still useful for bringing the maps into GMOD or CS:GO which do support static prop scaling.
