### ISSUE TITLE
Some tool textures replaces to different in Vtm:B maps

### ISSUE THREAD

**Issue by Psycho-A** [ata4/bspsrc#72]
Even if we disable "Fix tool texture" checkbox, textures like toolsclip, toolsnpcclip and others replaces to toolsskip or even nothing (no brush faces at all). How to force disable any "smart" behaviors on this and use what intended here? Version BSPSrc 1.2.1 didn't suffer this...

**Comment by rihi** [comment]
I've changed it so that the "Fix tool texture" option now again takes effect even if the game is Vtm:b. Note however, that you will probably still get poor results no matter if the option is enabled or not, as vtm:b has a lot of unique tool textures.

In the future, it'd be possible to add special support for all the unique tooltextures of the game, but for now this is the best we have.
